### ISSUE TITLE
Sign in loop

### ISSUE THREAD

**Issue by lokpbgg** [VShopApp/mobile#45]
When I try to log in it just resets and goes back to the sign in page.

**Comment by vascYT** [comment]
Good day,
this exact issue should be fixed with the latest update. Did you install it?

**Comment by lokpbgg** [comment]
I just tried it on the latest version and the problem is still happening.

**Comment by lokpbgg** [comment]
Sorry I dont know what im doing lol.
